url: "https://pamrosel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Lola Digital" # the name of your site, e.g. ACME Corp.
sass_dir: _sass
description: Pamela Rosel is a freelance designer based in Brisbane, Meanjin, interested in the intersection of design and development, creating meaningful experiences across branding and digital.
github_username: pamrosel
email: pamrosel.is@gmail.com
theme: null
